spring.application.name=SMInstagram
# Swagger UI

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springdoc.packagesToScan=com.example.sminstagram
springdoc.pathsToMatch=/**
springdoc.swagger-ui.urls-primary-name=default
springdoc.swagger-ui.custom-css-url=/swagger-custom.css

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${A}
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
app.cookie.secure=false



# k?t n?i database
# neondb
spring.datasource.url=${B}
spring.datasource.username=${C}
spring.datasource.password=${D}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

