spring.application.name=SMInstagram
# Swagger UI

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
springdoc.packagesToScan=com.example.sminstagram
springdoc.pathsToMatch=/**
springdoc.swagger-ui.urls-primary-name=default
springdoc.swagger-ui.custom-css-url=/swagger-custom.css

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=7a9f3c2e8b1d4f6a0e5c7b3d9f2a8c4e6b0d3f7a1c5e9b2d4f8a0c6e3b7d1f9
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
app.cookie.secure=false

# k?t n?i database
# neondb

spring.datasource.url=jdbc:postgresql://ep-long-meadow-a18jklgn-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_kdS2iCUBzR1h
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

